version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse_system
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - laravel
    depends_on:
      - db

  db:
    hostname: ${DB_HOST}
    image: postgres:alpine
    container_name: laravel_db
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST=${DB_HOST}
    volumes:
      - dbdata:/var/lib/pgsql
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: -p ${DB_PORT}
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: